<a href="https://colab.research.google.com/github/SakshiPunia314/SakshiPunia314/blob/main/Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import pandas as pd
from scipy.stats import zscore

#Load the New York City dataset
nyc_data = pd.read_csv("AB_NYC_2019.csv.zip")

# Display basic information about the dataset
print("Dataset Info:")
print(nyc_data.info())

# Check for any inconsistencies or anomalies in the data
print("\nData Integrity Check:")
#Check for unique values in a name column
print("Unique values in 'name' column:", nyc_data['name'].unique())

# Check for missing values
print("\nMissing Data Check:")
missing_data = nyc_data.isnull().sum()
print(missing_data)

# Impute missing values in 'reviews_per_month' column with the median
median_reviews_per_month = nyc_data['reviews_per_month'].median()
nyc_data['reviews_per_month'].fillna(median_reviews_per_month, inplace=True)

#to handle missingvalue in las_review coloum
mode_last_review=nyc_data['last_review'].mode()
nyc_data['last_review'].fillna(mode_last_review,inplace=True)

#replce empty cell with before value of the cuurent cell
nyc_data.fillna(method='bfill', inplace=True)
print("Data cleaning completed. Modified dataset saved as 'output.csv'.")


# Check if missing values were handled properly
print("\nMissing Data Check after handling:")
missing_data_after = nyc_data.isnull().sum()
print(missing_data_after)

# Check for duplicate records
print("\nDuplicate Removal:")
duplicates_count = nyc_data.duplicated().sum()
print("Number of duplicate records:", duplicates_count)

# Remove duplicate records
nyc_data.drop_duplicates(inplace=True)

#  Remove leading and trailing whitespaces from string columns
nyc_data['name'] =nyc_data['name'].str.strip()

# Check for outliers in price column
print("\nOutlier Detection:")
# Example: Use z-score to detect outliers in 'price' column
z_scores = zscore(nyc_data['price'])
outliers = (z_scores > 3) | (z_scores < -3)
outliers_count = outliers.sum()
print("Number of outliers in 'price' column:", outliers_count)

# Clip outliers in 'minimum_nights' column to a valid range
nyc_data['minimum_nights'] = nyc_data['minimum_nights'].clip(lower=1, upper=180)

# Save the cleaned dataset
nyc_data.to_csv("cleaned_nyc_dataset.csv", index=False)

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              48895 non-null  int64
 1   name                            48879 non-null  object
 2   host_id                         48895 non-null  int64
 3   host_name                       48874 non-null  object
 4   neighbourhood_group             48895 non-null  object
 5   neighbourhood                   48895 non-null  object
 6   latitude                        48895 non-null  float64
 7   longitude                       48895 non-null  float64
 8   room_type                       48895 non-null  object
 9   price                           48895 non-null  int64
 10  minimum_nights                  48895 non-null  int64
 11  number_of_reviews               48895 non-null  int64
 12  last_review                     38843 non-null  object
 13  reviews_per_month               38843 non-null  float64
 14  calculated_host_listings_count  48895 non-null  int64
 15  availability_365                48895 non-null  int64
dtypes: float64(3), int64(7), object(6)
memory usage: 6.0+ MB
None

Data Integrity Check:
Unique values in 'name' column: ['Clean & quiet apt home by the park' 'Skylit Midtown Castle'
 'THE VILLAGE OF HARLEM....NEW YORK !' ...
 'Sunny Studio at Historical Neighborhood'
 '43rd St. Time Square-cozy single bed'
 "Trendy duplex in the very heart of Hell's Kitchen"]

Missing Data Check:
id                                    0
name                                 16
host_id                               0
host_name                            21
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
last_review                       10052
reviews_per_month                 10052
calculated_host_listings_count        0
availability_365                      0
dtype: int64
Data cleaning completed. Modified dataset saved as 'output.csv'.

Missing Data Check after handling:
id                                 0
name                               0
host_id                            0
host_name                          0
neighbourhood_group                0
neighbourhood                      0
latitude                           0
longitude                          0
room_type                          0
price                              0
minimum_nights                     0
number_of_reviews                  0
last_review                       42
reviews_per_month                  0
calculated_host_listings_count     0
availability_365                   0
dtype: int64

Duplicate Removal:
Number of duplicate records: 0

Outlier Detection:
Number of outliers in 'price' column: 388